global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_interval: 5m
  group_wait: 30s
  receiver: prometheus-msteams-receiver
  repeat_interval: 5m
  routes:
  - receiver: prometheus-msteams-receiver
receivers:
- name: prometheus-msteams-receiver
  webhook_configs:
  - url: "http://prometheus-msteams:2000/alertmanager"
    send_resolved: true
  
# For slack integration
#  global:
#   resolve_timeout: 2m
# route:
#   group_by: ['alertname']
#   group_interval: 5m
#   group_wait: 30s
#   receiver: prometheus-slack
#   repeat_interval: 5m
# receivers:
# - name: prometheus-slack
#   slack_configs:
#   - api_url: ""
#     channel: '#alertmanager'
#     icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
#     send_resolved: true
