global:
  scrape_interval:     60s
  evaluation_interval: 60s

  external_labels:
      monitor_server: 'devops_server'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus-devops-server'
    scrape_interval: 60s
    static_configs:
         - targets: ['prometheus:9090']


  - job_name: 'cadvisor'
    scrape_interval: 60s
    static_configs:
          - targets: ['10.0.1.252:8080']
            labels:
              env: 'development'
              #instance: 'devops-server'

          - targets: ['172.31.15.111:8080']
            labels:
              env: 'development'
              #instance: 'development-server'

          - targets: ['10.0.0.211:8088']
            labels:
              env: 'production'
              #instance: 'production-1-server'

          - targets: ['10.0.1.188:8088']
            labels:
              env: 'production'
              #instance: 'production-2-server'

          - targets: ['10.0.0.141:8080']
            labels:
              env: 'production'
              #instance: 'web-server'

          - targets: ['10.0.1.15:8080']
            labels:
              env: 'production'
              #instance: 'openvpn-server'

  - job_name: 'node-exporter'
    scrape_interval: 60s
    static_configs:
          - targets: ['10.0.1.252:9100']
            labels:
              env: 'development'
              #instance: 'devops-server'

          - targets: ['172.31.15.111:9100']
            labels:
              env: 'development'
              #instance: 'development-server'

          - targets: ['10.0.0.211:9100']
            labels:
              env: 'production'
              #instance: 'production-server-1'

          - targets: ['10.0.1.188:9100']
            labels:
              env: 'production'
              #instance: 'production-server-2'

          - targets: ['10.0.0.141:9100']
            labels:
              env: 'production'
              #instance: 'web-server'

          - targets: ['10.0.1.15:9100']
            labels:
              env: 'production'
              #instance: 'openvpn-server'
